### ISSUE TITLE
Capnproto messages are not Send

### ISSUE THREAD

**Issue by danburkert** [dwrensha/capnproto-rust#23]
In trying to structure an app so that messages are read from a (TCP) stream, and then passed off to another thread for further processing, I'm running into issues because the message reader is not `Send`.  Is this intended, or perhaps fallout from the opt-in built-in changes?  For reference these are the errors I'm seeing when trying to move a message into a new thread:

```
error: the trait `core::marker::Send` is not implemented for the type `*const capnp::arena::SegmentReader`
error: the trait `core::marker::Send` is not implemented for the type `*const u8`
error: the trait `core::marker::Send` is not implemented for the type `*const capnp::layout::WirePointer`
```

**Comment by Vaelden** [comment]
If you try to pass a Reader, I think this is intended behaviour, as a Reader only holds references to an object that actually owns the data: `capnp::serialize::OwnedSpaceMessageReader`.
So if you want to defer processing to another task, you have to send the object that actually owns the data, or you would have lifetime problems (holding references to an out-of-scope object).

Here is an example:
```rust
use capnp::serialize::OwnedSpaceMessageReader;
use std::sync::Arc;
fn test<T: std::io::Reader>(reader: &mut T, sender: &std::sync::mpsc::Sender<OwnedSpaceMessageReader>) {
    // Example 1: spawn a new thread
    let message_reader = capnp::serialize::new_reader(reader, capnp::message::DEFAULT_READER_OPTIONS).unwrap();
    std::thread::Thread::spawn(move || {
        let my_struct_reader = message_reader.get_root::<my_struct::Reader>();
        // do further processing in this task
    });

    // Example 2: send to an existing thead
    let message_reader_2 = capnp::serialize::new_reader(reader, capnp::message::DEFAULT_READER_OPTIONS).unwrap();
    sender.send(message_reader_2).unwrap();
}
```

**Comment by dwrensha** [comment]
@Vaelden has it right. `MessageReader` is implemented for `SegmentArrayMessageReader` and `OwnedSpaceMessageReader`. The former cannot be `Send`, because it borrows the segments.

There's a similar situation for `MessageBuilder`, where `MallocMessageBuilder` is `Send` but `ScratchSpaceMallocMessageBuilder` is not.

@danburkert, from your error message, it looks like you are trying to send interior Reader refererences, e.g. `foo::Reader<'a>` where `Foo` is a struct defined in a `.capnp` file. These Readers cannot be `Send` because they do not own their data. Sadly, this means that if you want to do some processing of a message on one thread and some further processing on another thread, the only safe way to do it is to re-traverse the message on the second thread.

One way we could possibly work around this would be to support a special kind of `MessageReader` whose root is *not* the first word of the first segment. Then, after you're done working with the `OwnedSpaceMessageReader` on the first thread, you could move it into one of these special readers with its root set to the interior part of the message where the second thread needs to start working. This would eliminate the re-traversal work.

**Comment by dwrensha** [comment]
Nowadays (since https://github.com/dwrensha/capnproto-rust/commit/b1c54c9221de1d8ad976fa92ab58c66a6cda7b4d) `message::Reader` and `message::Builder` are generic structs rather than traits. Whether they are `Send` depends on the concrete implementations of the `ReaderSegments` and `Allocator` traits plugged in.

As has always been the case, generated builders and readers are not `Send`, because they are analogous to `&mut T` and `&T` where `T` is not `Sync`. If you want to send a capnproto value to another thread and not lose type information, you can write a generic wrapper struct that uses [`Owned`](https://docs.rs/capnp/0.8.1/capnp/traits/trait.Owned.html).

**Comment by ysimonson** [comment]
FWIW, I got it working by just instantiating `tokio_core::reactor::Core` and re-connecting to the server for each request. This gets around the issue mentioned in my prior comment, albeit with a substantial performance impact: https://github.com/indradb/indradb/blob/dc980cf4bacbcb94b5a26546e515481d1a6dd364/bin/src/common/client_datastore.rs#L43-L74
