### ISSUE TITLE
Supporting Rust's decoding/encoding infrastructure

### ISSUE THREAD

**Issue by caizixian** [dwrensha/capnproto-rust#24]
So that it can be used in rust-lang/rustc-serialize
rust-lang/rustc-serialize#35

**Comment by dwrensha** [comment]
A while back I wrote a post about why I'm not convinced that libserialize (which has since been renamed to rustc-serialize, apparently) is a good fit Cap'n Proto: http://dwrensha.github.io/capnproto-rust/2014/06/01/libserialize-traits.html

Perhaps things have changed since then, or perhaps you have a compelling use case. If so, I'm curious to learn more. :)

**Comment by caizixian** [comment]
Got it.
