### ISSUE TITLE
Best way to differentiate between types at runtime

### ISSUE THREAD

**Issue by jimfleming** [dwrensha/capnproto-rust#34]
[Let me know if there's a better place for these questions.]

What's the best way to handle different capnp message structs coming in from the same zmq socket? There doesn't seem to be a way to differentiate them before decoding. I see there's a `type_id` on the reader and there's also capnp generics, maybe a third approach?

In my previous implementation with json I had a top-level "request" object which contained a type id and a string blob. Then I would use a match on the type id to decode the inner string blob into a struct based on the type of request. (This was a hack to work around rustc-serialize limitations at the time.)

EDIT: Maybe unions? http://stackoverflow.com/questions/28149139/serializing-mutable-state-and-sending-it-asynchronously-over-the-network-with-ne#comment44738481_28156323

**Comment by dwrensha** [comment]
Yep, unions are likely what you want. If you want to handle two different structs of type A and B on the same connection, you can wrap them in a union C:

```
struct C {
  union {
      a @0 : A;
      b @1 : B;
   }
}
```
See also https://capnproto.org/language.html#unions .

In the Rust implementation, working with unions is particularly nice, because we take advantage of Rust's algebraic datatypes. So, on the receiving end, if you have `c : c::Reader` you can do

```
match c.which() {
   Ok(A(a)) => { ... }
   Ok(B(b)) => { ... }
   Err(NotInSchema(_)) => {...}
}
```

**Comment by jimfleming** [comment]
Whoa, `which` is handy and union looks like what I need. Thanks for the tips!
