### ISSUE TITLE
Consider merging with Serde

### ISSUE THREAD

**Issue by erasmospunk** [dwrensha/capnproto-rust#68]
The [Sedre](https://serde.rs/) library supports many serialization formats but not capnproto.

One useful feature is the [transcode](https://serde.rs/transcode.html) functionality where it is possible to convert from one format to the other.

**Comment by dwrensha** [comment]
Hi!

My impression is that Cap'n Proto would not be a very good fit for Serde integration, mainly because Cap'n Proto wants to define data types in schemas external to Rust code. I have [an old post](https://dwrensha.github.io/capnproto-rust/2014/06/01/libserialize-traits.html) on this topic. (The `libserialize` discussed there is now called [`rustc_serialize`](https://github.com/rust-lang-nursery/rustc-serialize), if I remember correctly.)

Do you have a specific use case in mind?

**Comment by burdges** [comment]
I'd think cap'n proto could generate the serde attributes from its schema, maybe useful if someone must work around company policies like always use json or xml for such and such.

**Comment by erasmospunk** [comment]
Good point about the schema, I initially thought that capnpc-rust could generate the needed `struct`s with Sedre's annotations & any runtime code. Not sure if this is simple, especially considering that Sedre does not support protocol buffers.

My use case is converting from JSON to Capnproto as an internal representation for microservices. Using the Sedre lib could potentially make the transcoding with less code.

If you think that this is something that does not make sense for this project, feel free to close this issue.

**Comment by dwrensha** [comment]
I do think think that it would be good to have JSON <--> Cap'n Proto support in capnproto-rust, but I'm not sure that it would make sense to involve Serde. I would probably start by looking at how [capnproto-c++ supports JSON encoding and decoding](https://github.com/sandstorm-io/capnproto/tree/b6d7079ac0cba1cf7003bbc6a889374d45a10087/c%2B%2B/src/capnp/compat).

**Comment by erasmospunk** [comment]
Thanks for feedback, closing this issue...

**Comment by dwrensha** [comment]
Today I came across [serde-protobuf](https://github.com/dflemstr/rq/tree/master/serde-protobuf). I'm not sure exactly what it does, but it seems relevant to this discussion.

**Comment by piaoger** [comment]
Do you have a plan to support JSON encoding and decoding in capnproto-rust?

**Comment by dwrensha** [comment]
@piaoger It would be good to have, but I don't have any immediate plans to work on it.

I think the way forward would be to implement [dynamic reflection](https://capnproto.org/cxx.html#dynamic-reflection) as in the C++ reference implementation, so that `to_json()` and `from_json()` functions could work for any type of message without needing any extra generated code.

**Comment by kaligrafy** [comment]
Any news on this?

**Comment by sffc** [comment]
Cap'n Proto with aligned data, so it has the capability to [return things like `&[u32]`](https://docs.rs/capnp/latest/capnp/primitive_list/struct.Reader.html#method.as_slice) on little-endian systems, which can be crucial for performance.

Serde on the other hand is capable of zero-copy deserializing `&[u8]` (and `&str`) but not anything wider than that. You would therefore be losing out on critical performance characteristics by trying to fit Cap'n Proto into Serde's data model.

It is possible to model slices on top of byte buffers by using unaligned reads, which incur a small performance penalty but in practice this penalty is often in the noise. The [`zerovec` crate](https://docs.rs/zerovec/latest/zerovec/) provides these abstractions so that you can use zero-copy deserialization with Serde. (Disclaimer: I am a maintainer of the zerovec crate.)

**Comment by burdges** [comment]
As an aside, we discussed multi- architecture layout ideas in https://internals.rust-lang.org/t/multi-architecture-layout/18538 which likely never happens in rustc, but maybe gives someone ideas.

**Comment by puremourning** [comment]
yeh, exactly! if a public implementation already exists that's equivalent to the c++ one, I haven't found it.

**Comment by dwrensha** [comment]
Yes, I would consider merging such a PR.

I guess it would probably make the most sense as a separate crate in the cargo workspace, because the required parsing logic is likely to require a nontrivial amount of code.

**Comment by puremourning** [comment]
Thanks.

> likely to require a nontrivial amount of code

yes, I'm afraid so. With the flattening and unions, it can be a little hairy. it's going to be about  1kloc + tests the way I've written in 🙈 .

When I have something that I think is roughly "complete" as a first pass, I'll open an unpolisheed PR as RFC and we can discuss/decide on factorings, direction etc. There are a couple of possible/open design decisions that you may wish to weigh in on. Initially it won't be very performant and perhaps not as flexible as the c++ implementation. But we can discuss that direction in a WIP PR with some commentary.
